server:
  port: 8080

mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml
spring:
  application:
    name: microcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/gobaby?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: hhd001 # 数据库连接密码


